apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: joget-app-argocd-joget
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/motrabelsi10/joget-project-argocd.git
    targetRevision: master
    path: manifests/joget-deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
